require 'wordlist/operators/concat'
require 'wordlist/operators/subtract'
require 'wordlist/operators/product'
require 'wordlist/operators/power'
require 'wordlist/operators/intersect'
require 'wordlist/operators/union'
require 'wordlist/operators/unique'
